{{- $kafkaProxy := (add1 .Values.kafkaProxy) | int }}
  {{- $root := . }}
  {{- range $i := untilStep 1 ($kafkaProxy) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $root.Values.brokerName }}-{{ $i }}.{{ $root.Values.clusterType }}.{{ $root.Values.domain }}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: {{ $root.Values.serviceAnnotations.awsLoadbalancerAdditionalResourceTags }}
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: {{ $root.Values.serviceAnnotations.awsLoadbalancerAccessLogEmitInterval }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: {{ $root.Values.serviceAnnotations.awsLoadbalancerCrossZoneLoadbalancingEnabled }}
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: {{ $root.Values.serviceAnnotations.awsLoadbalancerConnectionDrainingEnabled }}
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: {{ $root.Values.serviceAnnotations.awsLoadbalancerConnectionDrainingTimeout }}
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: {{ $root.Values.serviceAnnotations.awsLoadbalancerAccessLogEnabled }}
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: {{ $root.Values.serviceAnnotations.awsLoadbalancerAccessLogS3BucketName }}
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: {{ $root.Values.serviceAnnotations.awsLoadbalancerAccessLogS3BucketPrefix }}
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: {{ $root.Values.serviceAnnotations.awsLoadbalancerExtraSecurityGroups }}
  labels:
    app: kafka-proxy-{{ $i }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version }}
    heritage: {{ $root.Release.Service }}
    release: {{ $root.Release.Name }}
  name: {{ template "fullname"  $root }}-{{ $i }}
  namespace: {{  $root.Values.namespace }}
spec:
  type: {{ $root.Values.service.type}}
  loadBalancerSourceRanges: {{ $root.Values.loadBalancerSourceRanges }}
  sessionAffinity: {{ $root.Values.sessionAffinity}}
  ports:
    - name: health
      port: {{ $root.Values.service.healthPort }}
      protocol: TCP
    - name: kafka-proxy
      port: {{ $root.Values.service.servicePort }}
      protocol: TCP
  selector:
    app: {{ template "fullname" $root }}-{{ $i }}
{{- end }}
