---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-proxy-deployment-restart
  namespace: platform
rules:
  - apiGroups: ["'', apps, autoscaling, batch, extensions, policy, rbac.authorization.k8s.io"]
    resources: ["pods", "deployments", "replicasets"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-proxy-deployment-restart
  namespace: platform
subjects:
  - kind: ServiceAccount
    name: kafka-proxy-deployment-restart
    namespace: platform
roleRef:
  kind: Role
  name: kafka-proxy-deployment-restart
  apiGroup: rbac.authorization.k8s.io
